// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialDetail } from "./MaterialDetail";

export type GetMaterialResponse = { material: MaterialDetail };
