// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostSession } from "./HostSession";

export type GetSessionResponse = { session: HostSession | null };
