// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewSummary } from "./ReviewSummary";

export type GetSummaryResponse = { summary: ReviewSummary };
