// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Viewer } from "./Viewer";
import type { Workspace } from "./Workspace";

export type HostSession = { user: Viewer; workspace: Workspace };
