// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialStatus } from "./MaterialStatus";

export type MaterialSummary = {
  id: string;
  title: string;
  fileName: string;
  status: MaterialStatus;
  createdAt: string;
};
