// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginRpcRequest = {
  pluginId: string;
  workspaceId: string;
  method: string;
  params: unknown;
};
