// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewEvidence } from "./ReviewEvidence";
import type { ReviewStatus } from "./ReviewStatus";

export type ReviewDetail = {
  id: string;
  criterionId: string;
  criterionTitle: string;
  reviewQuestion: string;
  status: ReviewStatus;
  opinion: string;
  evidence: Array<ReviewEvidence>;
  createdAt: string;
  updatedAt: string;
};
