// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewStatus } from "./ReviewStatus";

export type SaveReviewParams = {
  criterionId: string;
  status: ReviewStatus;
  opinion: string;
  evidenceMaterialIds: Array<string>;
};
