// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDetail } from "./ReviewDetail";

export type SaveReviewResponse = { review: ReviewDetail };
