// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { DataroomRpcRequest } from "../types/DataroomRpcRequest";
import type { RpcResponse } from "../types/RpcResponse";
import { apiPost } from "../runtime/client";

/** @throws ApiError — non-2xx body is `ApiError`. */
export async function dataroomRpcHandler(request: DataroomRpcRequest): Promise<RpcResponse> {
  return apiPost<RpcResponse>(`/api/dataroom/rpc`, request);
}
