// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { GetSessionResponse } from "../types/GetSessionResponse";
import { apiGet } from "../runtime/client";

export async function getSessionHandler(): Promise<GetSessionResponse> {
  return apiGet<GetSessionResponse>(`/api/auth/session`);
}
