// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { HealthResponse } from "../types/HealthResponse";
import { apiGet } from "../runtime/client";

/** @throws ApiError — non-2xx body is `ApiError`. */
export async function healthHandler(): Promise<HealthResponse> {
  return apiGet<HealthResponse>(`/api/health`);
}
