// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { PluginRegistration } from "../types/PluginRegistration";
import { apiGet } from "../runtime/client";

export async function listPluginsHandler(): Promise<PluginRegistration[]> {
  return apiGet<PluginRegistration[]>(`/api/plugins`);
}
