// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { HostSession } from "../types/HostSession";
import type { LoginRequest } from "../types/LoginRequest";
import { apiPost } from "../runtime/client";

/** @throws ApiError — non-2xx body is `ApiError`. */
export async function loginHandler(input: LoginRequest): Promise<HostSession> {
  return apiPost<HostSession>(`/api/auth/login`, input);
}
