// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { LogoutResponse } from "../types/LogoutResponse";
import { apiPost } from "../runtime/client";

/** @throws ApiError — non-2xx body is `ApiError`. */
export async function logoutHandler(): Promise<LogoutResponse> {
  return apiPost<LogoutResponse>(`/api/auth/logout`, undefined);
}
