// AUTO-GENERATED by ts-server-fn. DO NOT EDIT.
import type { PluginRpcRequest } from "../types/PluginRpcRequest";
import type { RpcResponse } from "../types/RpcResponse";
import { apiPost } from "../runtime/client";

/** @throws ApiError — non-2xx body is `ApiError`. */
export async function pluginRpcHandler(request: PluginRpcRequest): Promise<RpcResponse> {
  return apiPost<RpcResponse>(`/api/plugins/rpc`, request);
}
